### PR TITLE
Remove disabled extensions from allowed_extensions

### LINKED ISSUE #438: Can't remove entries from file allowed_extensions list
Using Silverstripe in 4.6.

The documented method here to remove existing entries from the `allowed_extensions` list does not work: https://docs.silverstripe.org/en/4/developer_guides/files/allowed_file_types/

If I add, say:

```
SilverStripe\Assets\File:
  allowed_extensions:
    zip: false
```

Looking at the code, all it does is skip that new entry for `zip`. It doesn't check if zip is already in the list and remove it.

If that is the intended behaviour then perhaps the docs need to be clarified.

### PR DESCRIPTION
**Pull request by andrewandante**
Fixes #438 

Currently the docs example doesn't work: https://docs.silverstripe.org/en/4/developer_guides/files/allowed_file_types/#file-extensions-validation

It just skips over the value and leaves the original in the list. This change removes it from the core list.

### CODE REVIEW

File: tests/php/FileTest.php [hunk 1]
```diff
@@ -801,7 +801,7 @@ public function testRename()
     public function testGetAllowedExtensions($allowedExtensions, $expected)
     {
         Config::modify()->set(File::class, 'allowed_extensions', $allowedExtensions);
-        $this->assertSame($expected, $expected);
```
Comment (andrewandante) [inline tests/php/FileTest.php:804]: This is one of the funnier things I've ever had to fix in a PR 😆

Comment (maxime-rainville) [reply tests/php/FileTest.php:804]: :see_no_evil:

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
Good fix. This is probably worth putting into a patch release for order version. Can you retarget to the 1.7 branch?

**Comment by andrewandante** [comment]
Will do, just going to rebase 👍

**Review by maxime-rainville — APPROVED** [review]
Awesome!!! Merge on green.
